# C-PAC Testing Data Configuration File
# v1.6.2
# 
# this is a cross-section of HNU_1 datasets meant for the C-PAC release regression test

- anat:
    T1w: /ocean/projects/med220004p/shared/data_raw/CPAC-Regression/CORR/RawDataBIDS/HNU_1/sub-0025453/ses-1/anat/sub-0025453_ses-1_run-1_T1w.nii.gz
  creds_path: null
  func:
    rest_run-1:
      scan: /ocean/projects/med220004p/shared/data_raw/CPAC-Regression/CORR/RawDataBIDS/HNU_1/sub-0025453/ses-1/func/sub-0025453_ses-1_task-rest_run-1_bold.nii.gz
      scan_parameters:
        AcquisitionDuration: '10:00'
        AcquisitionMatrix: 64x64
        EchoTime: 0.03
        FieldofViewDimensions: 220x220
        FieldofViewShape: Rectangle
        FlipAngle: 90
        Instructions: '''Relax and remain still with your eyes open. Do not fall asleep
          and do not think about anything in particular.'''
        MagneicFieldSrengh: 3
        Manufacturer: GE
        ManufacturersModelName: Discovery MR750
        NumberOfSlices: 43
        NumberofMeasurements: 300
        ParallelAcquisition: 'Yes'
        ParallelAcquisitionTechnique: ASSET
        PhaseEncodingDirection: j-
        PixelBandwidth: 3437.5
        PixelSpacing: 3.4x3.4
        PlaneOrientationSequence: Axial
        PulseSequenceType: EPI
        ReceiveCoilName: 8 Chan
        ReceiveCoilType: Head
        RepetitionTime: 2.0
        ScanOptions: FS
        SliceAcquisitionOrder: Interleaved Ascending
        SliceEncodingDirection: k
        SliceThickness: 3.4
        SliceTiming:
        - 0.0
        - 1023.26
        - 46.51
        - 1069.77
        - 93.02
        - 1116.28
        - 139.53
        - 1162.79
        - 186.05
        - 1209.3
        - 232.56
        - 1255.81
        - 279.07
        - 1302.33
        - 325.58
        - 1348.84
        - 372.09
        - 1395.35
        - 418.6
        - 1441.86
        - 465.12
        - 1488.37
        - 511.63
        - 1534.88
        - 558.14
        - 1581.4
        - 604.65
        - 1627.91
        - 651.16
        - 1674.42
        - 697.67
        - 1720.93
        - 744.19
        - 1767.44
        - 790.7
        - 1813.95
        - 837.21
        - 1860.47
        - 883.72
        - 1906.98
        - 930.23
        - 1953.49
        - 976.74
        SpacingBetweenSlices: 3.4
        TaskDescription: ' During functional scanning, subjects were presented with
          a fixation cross and were instructed to keep their eyes open, relax and
          move as little as possible while observing the fixation cross. Subjects
          were also instructed not to engage in breath counting or meditation.'
        TaskName: rest
  site_id: HNU_1
  subject_id: sub-0025453
  unique_id: ses-1
- anat:
    T1w: /ocean/projects/med220004p/shared/data_raw/CPAC-Regression/CORR/RawDataBIDS/HNU_1/sub-0025428/ses-1/anat/sub-0025428_ses-1_run-1_T1w.nii.gz
  creds_path: null
  func:
    rest_run-1:
      scan: /ocean/projects/med220004p/shared/data_raw/CPAC-Regression/CORR/RawDataBIDS/HNU_1/sub-0025428/ses-1/func/sub-0025428_ses-1_task-rest_run-1_bold.nii.gz
      scan_parameters:
        AcquisitionDuration: '10:00'
        AcquisitionMatrix: 64x64
        EchoTime: 0.03
        FieldofViewDimensions: 220x220
        FieldofViewShape: Rectangle
        FlipAngle: 90
        Instructions: '''Relax and remain still with your eyes open. Do not fall asleep
          and do not think about anything in particular.'''
        MagneicFieldSrengh: 3
        Manufacturer: GE
        ManufacturersModelName: Discovery MR750
        NumberOfSlices: 43
        NumberofMeasurements: 300
        ParallelAcquisition: 'Yes'
        ParallelAcquisitionTechnique: ASSET
        PhaseEncodingDirection: j-
        PixelBandwidth: 3437.5
        PixelSpacing: 3.4x3.4
        PlaneOrientationSequence: Axial
        PulseSequenceType: EPI
        ReceiveCoilName: 8 Chan
        ReceiveCoilType: Head
        RepetitionTime: 2.0
        ScanOptions: FS
        SliceAcquisitionOrder: Interleaved Ascending
        SliceEncodingDirection: k
        SliceThickness: 3.4
        SliceTiming:
        - 0.0
        - 1023.26
        - 46.51
        - 1069.77
        - 93.02
        - 1116.28
        - 139.53
        - 1162.79
        - 186.05
        - 1209.3
        - 232.56
        - 1255.81
        - 279.07
        - 1302.33
        - 325.58
        - 1348.84
        - 372.09
        - 1395.35
        - 418.6
        - 1441.86
        - 465.12
        - 1488.37
        - 511.63
        - 1534.88
        - 558.14
        - 1581.4
        - 604.65
        - 1627.91
        - 651.16
        - 1674.42
        - 697.67
        - 1720.93
        - 744.19
        - 1767.44
        - 790.7
        - 1813.95
        - 837.21
        - 1860.47
        - 883.72
        - 1906.98
        - 930.23
        - 1953.49
        - 976.74
        SpacingBetweenSlices: 3.4
        TaskDescription: ' During functional scanning, subjects were presented with
          a fixation cross and were instructed to keep their eyes open, relax and
          move as little as possible while observing the fixation cross. Subjects
          were also instructed not to engage in breath counting or meditation.'
        TaskName: rest
  site_id: HNU_1
  subject_id: sub-0025428
  unique_id: ses-1
- anat:
    T1w: /ocean/projects/med220004p/shared/data_raw/CPAC-Regression/CORR/RawDataBIDS/HNU_1/sub-0025429/ses-1/anat/sub-0025429_ses-1_run-1_T1w.nii.gz
  creds_path: null
  func:
    rest_run-1:
      scan: /ocean/projects/med220004p/shared/data_raw/CPAC-Regression/CORR/RawDataBIDS/HNU_1/sub-0025429/ses-1/func/sub-0025429_ses-1_task-rest_run-1_bold.nii.gz
      scan_parameters:
        AcquisitionDuration: '10:00'
        AcquisitionMatrix: 64x64
        EchoTime: 0.03
        FieldofViewDimensions: 220x220
        FieldofViewShape: Rectangle
        FlipAngle: 90
        Instructions: '''Relax and remain still with your eyes open. Do not fall asleep
          and do not think about anything in particular.'''
        MagneicFieldSrengh: 3
        Manufacturer: GE
        ManufacturersModelName: Discovery MR750
        NumberOfSlices: 43
        NumberofMeasurements: 300
        ParallelAcquisition: 'Yes'
        ParallelAcquisitionTechnique: ASSET
        PhaseEncodingDirection: j-
        PixelBandwidth: 3437.5
        PixelSpacing: 3.4x3.4
        PlaneOrientationSequence: Axial
        PulseSequenceType: EPI
        ReceiveCoilName: 8 Chan
        ReceiveCoilType: Head
        RepetitionTime: 2.0
        ScanOptions: FS
        SliceAcquisitionOrder: Interleaved Ascending
        SliceEncodingDirection: k
        SliceThickness: 3.4
        SliceTiming:
        - 0.0
        - 1023.26
        - 46.51
        - 1069.77
        - 93.02
        - 1116.28
        - 139.53
        - 1162.79
        - 186.05
        - 1209.3
        - 232.56
        - 1255.81
        - 279.07
        - 1302.33
        - 325.58
        - 1348.84
        - 372.09
        - 1395.35
        - 418.6
        - 1441.86
        - 465.12
        - 1488.37
        - 511.63
        - 1534.88
        - 558.14
        - 1581.4
        - 604.65
        - 1627.91
        - 651.16
        - 1674.42
        - 697.67
        - 1720.93
        - 744.19
        - 1767.44
        - 790.7
        - 1813.95
        - 837.21
        - 1860.47
        - 883.72
        - 1906.98
        - 930.23
        - 1953.49
        - 976.74
        SpacingBetweenSlices: 3.4
        TaskDescription: ' During functional scanning, subjects were presented with
          a fixation cross and were instructed to keep their eyes open, relax and
          move as little as possible while observing the fixation cross. Subjects
          were also instructed not to engage in breath counting or meditation.'
        TaskName: rest
  site_id: HNU_1
  subject_id: sub-0025429
  unique_id: ses-1
- anat:
    T1w: /ocean/projects/med220004p/shared/data_raw/CPAC-Regression/CORR/RawDataBIDS/HNU_1/sub-0025452/ses-1/anat/sub-0025452_ses-1_run-1_T1w.nii.gz
  creds_path: null
  func:
    rest_run-1:
      scan: /ocean/projects/med220004p/shared/data_raw/CPAC-Regression/CORR/RawDataBIDS/HNU_1/sub-0025452/ses-1/func/sub-0025452_ses-1_task-rest_run-1_bold.nii.gz
      scan_parameters:
        AcquisitionDuration: '10:00'
        AcquisitionMatrix: 64x64
        EchoTime: 0.03
        FieldofViewDimensions: 220x220
        FieldofViewShape: Rectangle
        FlipAngle: 90
        Instructions: '''Relax and remain still with your eyes open. Do not fall asleep
          and do not think about anything in particular.'''
        MagneicFieldSrengh: 3
        Manufacturer: GE
        ManufacturersModelName: Discovery MR750
        NumberOfSlices: 43
        NumberofMeasurements: 300
        ParallelAcquisition: 'Yes'
        ParallelAcquisitionTechnique: ASSET
        PhaseEncodingDirection: j-
        PixelBandwidth: 3437.5
        PixelSpacing: 3.4x3.4
        PlaneOrientationSequence: Axial
        PulseSequenceType: EPI
        ReceiveCoilName: 8 Chan
        ReceiveCoilType: Head
        RepetitionTime: 2.0
        ScanOptions: FS
        SliceAcquisitionOrder: Interleaved Ascending
        SliceEncodingDirection: k
        SliceThickness: 3.4
        SliceTiming:
        - 0.0
        - 1023.26
        - 46.51
        - 1069.77
        - 93.02
        - 1116.28
        - 139.53
        - 1162.79
        - 186.05
        - 1209.3
        - 232.56
        - 1255.81
        - 279.07
        - 1302.33
        - 325.58
        - 1348.84
        - 372.09
        - 1395.35
        - 418.6
        - 1441.86
        - 465.12
        - 1488.37
        - 511.63
        - 1534.88
        - 558.14
        - 1581.4
        - 604.65
        - 1627.91
        - 651.16
        - 1674.42
        - 697.67
        - 1720.93
        - 744.19
        - 1767.44
        - 790.7
        - 1813.95
        - 837.21
        - 1860.47
        - 883.72
        - 1906.98
        - 930.23
        - 1953.49
        - 976.74
        SpacingBetweenSlices: 3.4
        TaskDescription: ' During functional scanning, subjects were presented with
          a fixation cross and were instructed to keep their eyes open, relax and
          move as little as possible while observing the fixation cross. Subjects
          were also instructed not to engage in breath counting or meditation.'
        TaskName: rest
  site_id: HNU_1
  subject_id: sub-0025452
  unique_id: ses-1
- anat:
    T1w: /ocean/projects/med220004p/shared/data_raw/CPAC-Regression/CORR/RawDataBIDS/HNU_1/sub-0025448/ses-1/anat/sub-0025448_ses-1_run-1_T1w.nii.gz
  creds_path: null
  func:
    rest_run-1:
      scan: /ocean/projects/med220004p/shared/data_raw/CPAC-Regression/CORR/RawDataBIDS/HNU_1/sub-0025448/ses-1/func/sub-0025448_ses-1_task-rest_run-1_bold.nii.gz
      scan_parameters:
        AcquisitionDuration: '10:00'
        AcquisitionMatrix: 64x64
        EchoTime: 0.03
        FieldofViewDimensions: 220x220
        FieldofViewShape: Rectangle
        FlipAngle: 90
        Instructions: '''Relax and remain still with your eyes open. Do not fall asleep
          and do not think about anything in particular.'''
        MagneicFieldSrengh: 3
        Manufacturer: GE
        ManufacturersModelName: Discovery MR750
        NumberOfSlices: 43
        NumberofMeasurements: 300
        ParallelAcquisition: 'Yes'
        ParallelAcquisitionTechnique: ASSET
        PhaseEncodingDirection: j-
        PixelBandwidth: 3437.5
        PixelSpacing: 3.4x3.4
        PlaneOrientationSequence: Axial
        PulseSequenceType: EPI
        ReceiveCoilName: 8 Chan
        ReceiveCoilType: Head
        RepetitionTime: 2.0
        ScanOptions: FS
        SliceAcquisitionOrder: Interleaved Ascending
        SliceEncodingDirection: k
        SliceThickness: 3.4
        SliceTiming:
        - 0.0
        - 1023.26
        - 46.51
        - 1069.77
        - 93.02
        - 1116.28
        - 139.53
        - 1162.79
        - 186.05
        - 1209.3
        - 232.56
        - 1255.81
        - 279.07
        - 1302.33
        - 325.58
        - 1348.84
        - 372.09
        - 1395.35
        - 418.6
        - 1441.86
        - 465.12
        - 1488.37
        - 511.63
        - 1534.88
        - 558.14
        - 1581.4
        - 604.65
        - 1627.91
        - 651.16
        - 1674.42
        - 697.67
        - 1720.93
        - 744.19
        - 1767.44
        - 790.7
        - 1813.95
        - 837.21
        - 1860.47
        - 883.72
        - 1906.98
        - 930.23
        - 1953.49
        - 976.74
        SpacingBetweenSlices: 3.4
        TaskDescription: ' During functional scanning, subjects were presented with
          a fixation cross and were instructed to keep their eyes open, relax and
          move as little as possible while observing the fixation cross. Subjects
          were also instructed not to engage in breath counting or meditation.'
        TaskName: rest
  site_id: HNU_1
  subject_id: sub-0025448
  unique_id: ses-1