name: Correlate Regression Test

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'branch, tag, or SHA'
        type: string
        required: true
      owner:
        description: 'owner on GitHub'
        type: string
        required: false
        default: "FCP-INDI"
      repo:
        description: 'repository on GitHub'
        type: string
        required: false
        default: "C-PAC"
      environment:
        description: 'Environment in which to run correlations'
        type: environment
        required: false
        default: ACCESS
      pipeline1:
        type: string
        required: true
      pipeline2:
        type: string
        required: true
      preconfig:
        type: string
        required: true
      data_source:
        type: string
        required: true


jobs:
  correlate:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment}}
    env:
      COMPARISON_PATH: ${{ secrets.COMPARISON_PATH }}
      GH_PAT: ${{ secrets.GH_PAT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3
      - name: Finalize run check
        uses: guibranco/github-status-action-v2@v1.1.7
        with:
          authToken: ${{ env.GH_PAT }}
          context: lite run ${{ inputs.preconfig }} ${{ inputs.data_source }}
          owner: ${{ inputs.owner }}
          repository: ${{ inputs.repo }}
          sha: ${{ inputs.ref }}
          state: success
          target_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}#artifacts
      - name: Correlating
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command_timeout: 200m
          script: |
            cd ${{ secrets.SSH_WORK_DIR }}
            if [ ! -d reg-suite ] ; then
                git clone https://github.com/${{ env.DASHBOARD_REPO }} reg-suite
            else
                cd reg-suite
                git pull origin main
                cd ..
            fi
            mkdir -p ${{ secrets.SSH_WORK_DIR }}/regtest_lite/${{ github.sha }}/correlations
            sbatch --export="HOME_DIR=${{ secrets.SSH_WORK_DIR }},IMAGE=${{ env.DOCKER_TAG }},OWNER=${{ github.repository_owner }},PATH_EXTRA=${{ secrets.GH_CLI_BIN_PATH }},REPO=$(echo ${{ github.repository }} | cut -d '/' -f 2),SHA=${{ github.sha }}" --output=${{ secrets.SSH_WORK_DIR }}/regtest_lite/${{ github.sha }}/logs/out.log --error=${{ secrets.SSH_WORK_DIR }}/regtest_lite/logs/${{ github.sha }}/error.log slurm_testing/.github/scripts/launch_regtest_lite.SLURM

        # run: |
        #   echo "Correlating lite regression runs"
        #   echo "(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧"
        #   echo "Correlating ${{ inputs.pipeline1 }} × ${{ inputs.pipeline2 }} for ${{ inputs.owner}}/${{ inputs.repo }}@${{ inputs.ref }}"
        #   # 
      # - uses: actions/upload-artifact@v3
      #   if: always()
      #   with:
      #     name: logs
      #     path: output/*/*/log/
