name: Correlate Regression Test

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'branch, tag, or SHA'
        type: string
        required: true
      owner:
        description: 'owner on GitHub'
        type: string
        required: false
        default: "FCP-INDI"
      repo:
        description: 'repository on GitHub'
        type: string
        required: false
        default: "C-PAC"
      environment:
        description: 'Environment in which to run correlations'
        type: environment
        required: false
        default: ACCESS
      pipeline1:
        type: string
        required: true
      pipeline2:
        type: string
        required: true
      preconfig:
        type: string
        required: true
      data_source:
        type: string
        required: true


jobs:
  correlate:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3
      - name: Finalize run check
        uses: guibranco/github-status-action-v2@v1.1.7
        with:
          authToken: ${{ secrets.GH_PAT }}
          context: lite run ${{ inputs.preconfig }} ${{ inputs.data_source }}
          owner: ${{ inputs.owner }}
          repository: ${{ inputs.repo }}
          sha: ${{ inputs.ref }}
          state: success
          target_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}#artifacts
      - name: Correlating
        run: |
          echo "Correlating lite regression runs"
          echo "(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧"
          echo "Correlating ${{ inputs.pipeline1 }} × ${{ inputs.pipeline2 }} for ${{ inputs.owner}}/${{ inputs.repo }}@${{ inputs.ref }}"
          # python3 reg-suite/main.py correlate --pipeline1 $GITHUB_WORKSPACE/output/default/HNU_1 --pipeline2 $GITHUB_WORKSPACE/lite/default/HNU_1--workspace $GITHUB_WORKSPACE
      # - uses: actions/upload-artifact@v3
      #   if: always()
      #   with:
      #     name: logs
      #     path: output/*/*/log/
