name: Initiate check
run-name: ${{ inputs.job }} ${{ inputs.task }} initiated on ${{ inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      job:
        description: SLURM job
        type: string
        required: true
      task:
        description: run or correlate
        type: string
        required: true
      ref:
        description: 'branch, tag, or SHA'
        type: string
        required: true
      owner:
        description: 'owner on GitHub'
        type: string
        required: false
        default: "FCP-INDI"
      repo:
        description: 'repository on GitHub'
        type: string
        required: false
        default: "C-PAC"
      environment:
        description: 'Environment in which to run correlations'
        type: environment
        required: false
        default: ACCESS
      preconfig:
        type: string
        required: true
      data_source:
        type: string
        required: true

jobs:
  initiate:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment}}
    name: Running ${{ inputs.job }} on ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3
      - name: Initiate check
        uses: guibranco/github-status-action-v2@v1.1.7
        with:
          authToken: ${{ secrets.GH_PAT }}
          context: lite ${{ inputs.task }} ${{ inputs.preconfig }} ${{ inputs.data_source }}
          description: ${{ inputs.job }} on ${{ inputs.environment }}
          owner: ${{ inputs.owner }}
          repository: ${{ inputs.repo }}
          sha: ${{ inputs.ref }}
          state: pending
