name: Run launch status update

on:
  workflow_dispatch:
    inputs:
      ref:
        description: branch, tag, or SHA
        type: string
        required: true
      owner:
        description: owner on GitHub
        type: string
        required: false
        default: FCP-INDI
      repo:
        description: repository on GitHub
        type: string
        required: false
        default: C-PAC
      environment:
        description: Environment in which to run correlations
        type: environment
        required: false
        default: ACCESS
      status:
        type: choice
        options:
          - success
          - failure
          - pending

jobs:
  status_update:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment}}
    name: Update launch status
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3
      - name: Finalize run check
        uses: guibranco/github-status-action-v2@v1.1.7
        with:
          authToken: ${{ secrets.GH_PAT }}
          context: Launch lite regression test
          owner: ${{ inputs.owner }}
          repository: ${{ inputs.repo }}
          sha: ${{ inputs.ref }}
          state: ${{ inputs.status }}
          target_url: https://github.com/${{ inputs.owner }}/regtest-runlogs/tree/${{ inputs.repo}}_${{ inputs.ref }}/launch
