name: Update Repository URL

on:
  pull_request:

jobs:
  update-repo-url:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Update repository URL
        env:
          GITHUB_BASE_LOGIN: ${{ github.event.pull_request.base.repo.owner.login }}
          GITHUB_BASE_REPO_NAME: ${{ github.event.pull_request.base.repo.name }}
          GITHUB_REPO: ${{ github.event.pull_request.head.repo.full_name }}
          GH_PAT: ${{ secrets.GH_PAT }}
          HEAD_REF: ${{ github.head_ref }}
        run: |
          TARGET_REPO_URL="https://github.com/${GITHUB_BASE_LOGIN}/${GITHUB_BASE_REPO_NAME}"

          # Update the repository field in pyproject.toml
          if grep -q '^repository = ' pyproject.toml; then
            echo "Updating repository URL in pyproject.toml..."
            sed -i "s|^repository = \".*\"|repository = \"$TARGET_REPO_URL\"|" pyproject.toml
          else
            echo "Adding repository URL to pyproject.toml..."
            echo "repository = \"$TARGET_REPO_URL\"" >> pyproject.toml
          fi

          # Commit and push changes
          git config --local user.email "88335502+ChildMindInstituteCNL@users.noreply.github.com"
          git config --local user.name "🐈 Theodore"
          git remote set-url --push origin "https://${GH_PAT}@github.com/${GITHUB_REPO}"
          git add pyproject.toml
          git commit -m ":twisted_rightwards_arrows: Update repository URL to PR target."
          git push origin HEAD:"${HEAD_REF}"
