name: Test run failed

on:
  workflow_dispatch:
    inputs:
      log:
        description: run log
        type: string
        required: true
      ref:
        description: 'branch, tag, or SHA'
        type: string
        required: true
      owner:
        description: 'owner on GitHub'
        type: string
        required: false
        default: "FCP-INDI"
      repo:
        description: 'repository on GitHub'
        type: string
        required: false
        default: "C-PAC"
      environment:
        description: 'Environment in which to run correlations'
        type: environment
        required: false
        default: ACCESS

jobs:
  correlate:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3
      - name: Finalize run check
        uses: guibranco/github-status-action-v2@v1.1.7
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: Run regression test lite
          description: ${{ inputs.log }}
          owner: ${{ inputs.owner }}
          repository: ${{ inputs.repo }}
          sha: ${{ inputs.ref }}
          state: failure
